### ISSUE TITLE
Enclosure Files

### ISSUE THREAD

**Issue by perigoso** [openeew/openeew-sensor#15]
Sharing G-code is not ideal, it is machine specific, in general github should be used with source files, and avoid compiled files, generated files, binaries, etc.

I propose the models be uploaded on STL and perhaps STEP format only.

**Comment by perigoso** [comment]
Noting, STL files are akin to binaries, but it is the closest we get for a source file for this.

**Comment by andygrillo** [comment]
ahh yes, my mistake. I will correcvt.

**Comment by andygrillo** [comment]
done https://github.com/openeew/openeew-sensor/tree/master/enclosure
