### ISSUE TITLE
Missing bypass capacitors on the accelerometer chip power supply and voltage reference pins.

### ISSUE THREAD

**Issue by gareth2020** [openeew/openeew-sensor#17]
The noise performance might be worse than the specification because of missing bypass capacitors on the accelerometer chip power supply and voltage reference pins.

Figure 59 in https://www.analog.com/media/en/technical-documentation/data-sheets/adxl354_adxl355.pdf  suggests 2 bypass capacitors should be used for each power supply near to the ADXL355. i.e. 0ne 0.1uF (100nF) capacitor and one 1 uF capacitor.  However the OpenEEW schematic only seems to show 100nF capacitors connected to pins 5,8,10 and 11 of U3.
![image](https://user-images.githubusercontent.com/70943470/92507606-23ee5d80-f1ff-11ea-93c4-cc8bb1728a71.png)
![image](https://user-images.githubusercontent.com/70943470/92507813-792a6f00-f1ff-11ea-9f0b-c74094bf208c.png)

Analog Devices, probably characterized the noise spectral density for ±2 g range as 22.5 μg/√Hz
by using the circuit shown in Figure 59 of https://www.analog.com/media/en/technical-documentation/data-sheets/adxl354_adxl355.pdf. If the 1u F capacitors are not present, then the noise spectral density might be worse and the signal might be less immune to power supply noise e.g. from other electrical activity on the pcb and from radio frequency interference and from noise on the 5V power input.

For more on why two capacitors per voltage pin (and how to place and rout them) see https://www.analog.com/media/en/training-seminars/tutorials/MT-101.pdf 
e.g. "Low  frequency  noise  requires  larger  electrolytic  capacitors  which  act  as  charge  reservoirs  to  transient  currents.  High  frequency  power  supply  noise  is  best  reduced  with  low  inductance  surface  mount  ceramic  capacitors  connected  directly  to  the  power  supply  pins  of  the  IC. "  
e.g. "The purpose of the large capacitor is to be a reservoir of charge to supply the instantaneous charge requirements of the circuits locally so the charge need not come through the inductance of the power trace"

Reliability of the OpenEEW sensor might also be improved with two capacitors per voltage pin because when one of the capacitors fails it might not causing too much damage to the noise performance. If there was only one capacitor then the noise performance might be damaged too much if it failed.

**Comment by gareth2020** [comment]
It is hard to tell if the loss of noise performance and immunity will matter in this application. It might not because most local noise (mechanical or electrical) will not correlate between sites.  

It is also interesting to note that the Analog Devices evaluation board has two capacitors per voltage pin but they are not different.  See https://www.analog.com/media/en/technical-documentation/user-guides/EVAL-ADXL354-355-UG-1030.pdf  
![image](https://user-images.githubusercontent.com/70943470/92508609-d5da5980-f200-11ea-9c03-8a6a489c228e.png)

i.e. the evaluation board does not seem to match Figure 59 of https://www.analog.com/media/en/technical-documentation/data-sheets/adxl354_adxl355.pdf.


I have sent a query to Analog Devices Technical Support about this mismatch. Analog Devices: Case #(SR-186103-W5C8Y4)

This was the reply:
_Hello Gareth,
have you experienced such a degradation of performances or is it just hypothetical? As I said before, this breakout board is designed to support different mems with a common BoM.

Also please consider that these EVAL board are not designed to be integrated into a product and they come as it is.

This kit instead is specific for the ADXL-355
https://urldefense.proofpoint.com/v2/url?u=https-3A__www.analog.com_en_design-2Dcenter_evaluation-2Dhardware-2Dand-2Dsoftware_evaluation-2Dboards-2Dkits_EVAL-2DADXL355-2DPMDZ.html&d=DwIFAg&c=jf_iaSHvJObTbx-siA1ZOg&r=BNSi0RLDXywCVDeiXDJV-QTNF_9CBQjfLItfrVCJwho&m=InJ2SnAYkIPzK4qIO0t5JpuxdxNQC41MWLLvil3haCc&s=OZ58kHG_AnoyYVWj_P3e_FZCvnpG0e5nw4wzeJ0_rhg&e= 

Sincerely,
Rocco Marco Guglielmi
EMEA Centralized Applications Center (CAC)
Analog Devices
CIC.emea@analog.com<mailto:CIC.emea@analog.com>_

**Comment by gareth2020** [comment]
There is another eval board https://wiki.analog.com/_media/resources/eval/user-guides/eval-adicup360/hardware/adxl355/02_043217b_top.pdf   which has 10uF and a 0.1uF connected to each supply pin:
![image](https://user-images.githubusercontent.com/70943470/92506920-17b5d080-f1fe-11ea-8f00-cdad68bd6310.png)

Also notice the ferrite bead between VDD and the analog supply pin, and between VSS and AGND

**Comment by gareth2020** [comment]
We could see if **adding**  (not changing) 1uF capacitors or a 10 uF capacitors has any affect on the noise amplitude in the /sensor-traces?orgId=2&refresh=5s  
( Turing a light switch on an off repeatedly is one way to create RFI  and see if the bigger capacitors can remove more of it from the /sensor-traces?orgId=2&refresh=5s)
(We could also look at the affect of adding these capacitors on sensor trace noise when driving the LEDs and Buzzer )

We could also try adding the ferrite beads - but that might be impossible on the current pcb.

**Comment by perigoso** [comment]
Reopened, there are still some tests that can be done

**Comment by andygrillo** [comment]
@perigoso you mean testing the board as we have it now without bypass capacitors, against a revision with the bypass capacitors ?

**Comment by perigoso** [comment]
there was mention of experimenting with 1uF and 10uF, that's what i meant.
though imo there isn't really a need for this

**Comment by gareth2020** [comment]
The analog supply to the ADXL355 needs a ferrite in the analog return path as well to create a clean AGND .  AGND is also where the capacitors connected to V1PANA and VSUPPLY should be connected. See https://wiki.analog.com/_media/resources/eval/user-guides/eval-adicup360/hardware/adxl355/02_043217b_top.pdf
Layout advice is given in https://www.analog.com/media/en/training-seminars/tutorials/MT-101.pdf 

I have the two EVAL-ADXL355-PMDZ boards if looking at it will help.

**Comment by perigoso** [comment]
I think we can close this, If we end up doing further testing or find issues we can take a further look, but for now this should be resolved.
