### ISSUE TITLE
add certificates for secure TLS/SSL connection with MQTT broker

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#18]
Allow the option of using MQTT certificates for secure connection to the server:

http://www.iotsharing.com/2017/08/how-to-use-esp32-mqtts-with-mqtts-mosquitto-broker-tls-ssl.html
http://www.steves-internet-guide.com/creating-and-using-client-certificates-with-mqtt-and-mosquitto/

These certificates would need to be loaded into the SPIFFS memory of the ESP32

**Comment by johnwalicki** [comment]
Firmware v1.4.0 included the Watson IoT Server certificate.  
For remote subscribed MQTT topics, that certificate allows the device to confirm the MQTT messages were from a trusted host.
Closing this Issue.  If we want to generate client certificates, open a new GitHub issue in the openeew/firmware repo.
