### ISSUE TITLE
Create final Kicad schematic for V1

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#25]
- ETH pins correct
- BUZZ pin change (for GPS serial)
- INT pin change (for GPS serial)
- add GPS serial header

![image (8)](https://user-images.githubusercontent.com/6279965/94502215-4acdfd00-01c9-11eb-90ea-27032e9f1257.png)

**Comment by perigoso** [comment]
Release Candidate no-2

[pcb.pdf](https://github.com/openeew/openeew-sensor/files/5308695/pcb.pdf)
