### ISSUE TITLE
Add 'esp-touch' wifi provisioning

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#29]

**Comment by johnwalicki** [comment]
I have added SmartConfig support in https://github.com/openeew/openeew-sensor/commit/366b7a4d644c79555954151cfd7f51ae9ace5994

**Comment by johnwalicki** [comment]
Flutter implementation is under development.  Follow progress here:
https://github.com/openeew/openeew-provisioner/

**Comment by johnwalicki** [comment]
SmartConfig is incorporated into the firmware.  We also have implemented a mobile app to send SmartConfig wifi ssid/password.
Closing ticket.
