### ISSUE TITLE
Select 31.25hz as default sample rate for accelerometer

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#30]

**Comment by johnwalicki** [comment]
I have set the default ADXL355 sample rate to 31.25hz in my branch of the sensor firmware

**Comment by andygrillo** [comment]
Perfect. When you add your code we can close this

**Comment by johnwalicki** [comment]
Done in https://github.com/openeew/openeew-sensor/commit/743c799804bbe61c976c1379f9a6a67a29fad67d#diff-753f644347e5c67177545d055de8098e28ebba7f7b3d18d1c42fa5e27c5d84c4
