### ISSUE TITLE
Add OTA feature to the firmware

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#31]

**Comment by johnwalicki** [comment]
The original title of this GitHub issue was "Add OTA feature > to OpenEEW detection-docker"
Let's break that into two topics.  First let's work on OTA Firmware Upgrades. Then let's worry about docker.
I've changed the title.

**Comment by johnwalicki** [comment]
The current firmware checks during device activation if a newer version of firmware is available.  That check works but doesn't yet invoke the OTA upgrade.

**Comment by johnwalicki** [comment]
I've been reading the OTA documentation at
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html

**Comment by johnwalicki** [comment]
Complete - Merged - Closing via PR #50
