### ISSUE TITLE
Program RGB Leds for debugging

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#52]
This is a discussion for what the LEDs could indicate on the sensor board, to help users understand the status of the device.

**Connection indicators**
- [ ] breathing DIM CYAN: searching for WiFi
- [ ] static DIMCYAN: connected to WiFi
- [ ] breathing DIM PURPLE: can't connect to Wifi
- [ ] blinking DIM BLUE: everytime a msg is sent to cloud (1s)

**Alarm indicators** (fast blinking) - colors to be based on [modified Mercalli scale] (https://www.usgs.gov/media/images/modified-mercalli-intensity-mmi-scale-assigns-intensities)
- [ ] blinking BRIGHT RED: strong shaking expected here
- [ ] blinking BRIGHT ORANGE: medium shaking expected here
- [ ] blinking BRIGHT GREEN: weak shaking expected here

**Other indicators**
- [ ] 3 blinks YELLOW: (during setup loop by confirming with accelerometer values) - device is properly installed horizontally on vertical surface

**Comment by johnwalicki** [comment]
In this initial [Blink NeoPixel LED Status stages commit](https://github.com/openeew/openeew-sensor/commit/9c455e9434fc359a945d849a01808d64c77beaf4#diff-c3bf47ea1f4a4a605470313cacb3a44f4a461f68c6faeab07e737610cb5ac835) from several weeks ago, I emulated the Particle Photon color indicators from
https://docs.particle.io/tutorials/device-os/led/photon/

**Comment by johnwalicki** [comment]
I like your LED color proposals.

**Comment by johnwalicki** [comment]
Firmware v1.3.0 has been published
This Issue has been closed via https://github.com/openeew/openeew-sensor/pull/61
