### ISSUE TITLE
Create firmware variant for standard MQTT broker

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#59]
To allow for non-Watson IoT connections (eg. Mosquitto MQTT), it would be good to have a variant of the[ Watson IoT firmware](https://github.com/openeew/openeew-sensor/tree/master/firmware/WatsonIoT) that allows it to connect to a generic MQTT broker.

This would allow for connection to any remote or local server running [Mosquitto](https://mosquitto.org/), or another MQTT broker, rather than a specific cloud provider.

**Comment by johnwalicki** [comment]
To run an MQTT broker on your local subnet (for instance on a Raspberry Pi), I have made the minimum number of changes to the production firmware via this patch.  Essentially its 3 #ifdefs
Toggle #define LOCALNET in config.h

There's a patch to the version140 branch:
Run a MQTT Broker on a local subnet
https://github.com/openeew/openeew-sensor/commit/df6158a5a825ed4111e3dbc4cf5d02b29ca863e5

**Comment by johnwalicki** [comment]
Thanks to @andygrillo  for some inspiration
