### ISSUE TITLE
Change RMII pins in Kicad layout

### ISSUE THREAD

**Issue by andygrillo** [openeew/openeew-sensor#8]
The TXD1 pin from the ESP32 should go to the TXD1 pin in the LAN8720 module.
Similarly, the TXD0 pin should also go to the TXD0 pin in the LAN8720.

Currently we have these crossed:
![image](https://user-images.githubusercontent.com/6279965/90445533-6f509880-e0a5-11ea-8b6a-68f77e592681.png)

Its not possible to reassign these pins in code because the ESP32 has a fixed RMII bus, so the wiring must be done correctly.

**Comment by perigoso** [comment]
This was one thing in particular that i wanted to ask when i ported the schematic, makes sense now.

**Comment by andygrillo** [comment]
Yes, was our mistake. Its a shame because we wanted to test the LAN8720

**Comment by perigoso** [comment]
Check If this is the only erroneous connection in the RMII
